create unique index if not exists uq_reservation_charges_id_workspace_id
    on public.reservation_charges (id, workspace_id);

create table if not exists public.reservation_charge_payments (
    id bigint generated by default as identity primary key,
    workspace_id bigint not null,
    charge_id bigint not null,
    amount numeric(12, 2) not null,
    currency_code varchar(10) not null,
    payment_method varchar(30) not null,
    paid_at timestamptz not null,
    notes text,
    registered_by_user_id bigint not null,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint fk_reservation_charge_payments_charge
        foreign key (charge_id, workspace_id)
        references public.reservation_charges(id, workspace_id)
        on delete cascade,
    constraint fk_reservation_charge_payments_workspace
        foreign key (workspace_id)
        references public.workspaces(id)
        on delete cascade,
    constraint fk_reservation_charge_payments_registered_by_user
        foreign key (registered_by_user_id)
        references public.usuarios(id)
        on delete restrict,
    constraint chk_reservation_charge_payments_amount
        check (amount > 0),
    constraint chk_reservation_charge_payments_currency_code
        check (
            currency_code in (
                'USD', 'MXN', 'GTQ', 'HNL', 'NIO', 'CRC', 'PAB', 'DOP', 'COP',
                'VES', 'PEN', 'BOB', 'CLP', 'ARS', 'PYG', 'UYU', 'BRL'
            )
        ),
    constraint chk_reservation_charge_payments_payment_method
        check (payment_method in ('efectivo', 'tarjeta', 'transferencia', 'otro'))
);

create index if not exists idx_reservation_charge_payments_workspace_id
    on public.reservation_charge_payments (workspace_id);

create index if not exists idx_reservation_charge_payments_charge_id
    on public.reservation_charge_payments (charge_id);

create index if not exists idx_reservation_charge_payments_paid_at
    on public.reservation_charge_payments (paid_at desc);

drop trigger if exists trg_reservation_charge_payments_updated_at on public.reservation_charge_payments;
create trigger trg_reservation_charge_payments_updated_at
before update on public.reservation_charge_payments
for each row
execute function public.set_updated_at();

insert into public.reservation_charge_payments (
    workspace_id,
    charge_id,
    amount,
    currency_code,
    payment_method,
    paid_at,
    notes,
    registered_by_user_id
)
select
    rc.workspace_id,
    rc.id,
    coalesce(rc.total_billed_amount, rc.amount, 0),
    upper(coalesce(rc.currency_code, 'CRC')),
    coalesce(rc.payment_method, 'otro'),
    coalesce(rc.paid_at, rc.updated_at, rc.created_at, now()),
    'Pago migrado desde factura previamente marcada como pagada.',
    rc.registered_by_user_id
from public.reservation_charges rc
where rc.payment_status = 'pagado'
  and rc.charge_decision = 'cobrable'
  and not exists (
      select 1
      from public.reservation_charge_payments rcp
      where rcp.charge_id = rc.id
        and rcp.workspace_id = rc.workspace_id
  );

create or replace view public.reservation_charge_financials as
with payment_agg as (
    select
        rcp.workspace_id,
        rcp.charge_id,
        coalesce(sum(rcp.amount), 0)::numeric(12, 2) as paid_amount,
        count(*)::int as payment_count,
        max(rcp.paid_at) as last_payment_at
    from public.reservation_charge_payments rcp
    group by rcp.workspace_id, rcp.charge_id
)
select
    rc.workspace_id,
    rc.id as charge_id,
    rc.reservation_id,
    rc.currency_code,
    rc.payment_status,
    rc.payment_method,
    rc.paid_at,
    rc.charge_decision,
    coalesce(rc.total_billed_amount, rc.amount, 0)::numeric(12, 2) as total_billed_amount,
    coalesce(pa.paid_amount, 0)::numeric(12, 2) as paid_amount,
    greatest(
        coalesce(rc.total_billed_amount, rc.amount, 0)::numeric(12, 2) -
        coalesce(pa.paid_amount, 0)::numeric(12, 2),
        0::numeric
    )::numeric(12, 2) as outstanding_amount,
    coalesce(pa.payment_count, 0) as payment_count,
    pa.last_payment_at,
    case
        when rc.charge_decision = 'exonerado' then 'exonerado'
        when rc.payment_status = 'anulado' then 'anulado'
        when greatest(
            coalesce(rc.total_billed_amount, rc.amount, 0)::numeric(12, 2) -
            coalesce(pa.paid_amount, 0)::numeric(12, 2),
            0::numeric
        ) = 0::numeric then 'pagado'
        when coalesce(pa.paid_amount, 0)::numeric(12, 2) > 0::numeric then 'parcial'
        else 'pendiente'
    end as financial_status
from public.reservation_charges rc
left join payment_agg pa
    on pa.charge_id = rc.id
   and pa.workspace_id = rc.workspace_id;

create or replace view public.vw_kpi_reservation_facts as
select
    r.workspace_id,
    r.id as reservation_id,
    r.fecha as reservation_date,
    r.created_at as reservation_created_at,
    r.updated_at as reservation_updated_at,
    r.estado as reservation_status,
    r.appointment_outcome,
    r.tipo_atencion,
    r.tipo_consulta,
    r.confirmed_at,
    r.confirmed_by_user_id,
    r.cancelled_at,
    r.cancelled_by_user_id,
    r.cancellation_reason,
    r.checked_in_at,
    r.completed_at,
    r.outcome_recorded_at,
    r.outcome_recorded_by_user_id,
    r.usuario_id as reservation_user_id,
    u.nombre as reservation_user_name,
    r.paciente_id,
    p.nombre as patient_name,
    r.sala_id as room_id,
    s.nombre as room_name,
    s.estado as room_status,
    s.sucursal_id as branch_id,
    su.nombre as branch_name,
    greatest(
        0,
        floor(extract(epoch from (r.hora_fin - r.hora_inicio)) / 60)
    )::int as duration_minutes,
    rc.id as charge_id,
    rc.payment_status,
    rc.payment_method,
    coalesce(rcf.last_payment_at, rc.paid_at) as paid_at,
    rc.currency_code,
    rc.charge_decision,
    rc.pricing_mode,
    rcf.financial_status,
    coalesce(rcf.paid_amount, 0) as paid_amount,
    coalesce(rcf.outstanding_amount, 0) as outstanding_amount,
    coalesce(rcf.payment_count, 0) as payment_count,
    rcf.last_payment_at,
    coalesce(rc.room_charge_amount, 0) as room_charge_amount,
    coalesce(rc.supplies_total_amount, 0) as supplies_total_amount,
    coalesce(rc.supplies_total_cost, 0) as supplies_total_cost,
    coalesce(rc.total_billed_amount, rc.amount, 0) as total_billed_amount,
    coalesce(rcf.paid_amount, 0) as paid_revenue,
    case
        when rc.charge_decision = 'cobrable'
            then coalesce(rcf.outstanding_amount, 0)
        else 0
    end as pending_revenue,
    case
        when rc.charge_decision = 'exonerado'
            then coalesce(rc.total_billed_amount, rc.amount, 0)
        else 0
    end as exonerated_amount,
    case
        when rc.charge_decision = 'cobrable'
             and coalesce(rc.total_billed_amount, rc.amount, 0) > 0
             and coalesce(rcf.paid_amount, 0) > 0
            then round(
                (
                    least(
                        coalesce(rcf.paid_amount, 0),
                        coalesce(rc.total_billed_amount, rc.amount, 0)
                    ) / coalesce(rc.total_billed_amount, rc.amount, 0)
                ) * (
                    coalesce(rc.total_billed_amount, rc.amount, 0) -
                    coalesce(rc.supplies_total_cost, 0)
                ),
                2
            )
        else null
    end as gross_margin_amount
from public.reservas r
left join public.usuarios u
    on u.id = r.usuario_id
left join public.pacientes p
    on p.id = r.paciente_id
   and p.workspace_id = r.workspace_id
left join public.salas s
    on s.id = r.sala_id
   and s.workspace_id = r.workspace_id
left join public.sucursales su
    on su.id = s.sucursal_id
left join public.reservation_charges rc
    on rc.reservation_id = r.id
   and rc.workspace_id = r.workspace_id
left join public.reservation_charge_financials rcf
    on rcf.charge_id = rc.id
   and rcf.workspace_id = rc.workspace_id;
