alter table public.inventory_items
    add column if not exists descripcion text null,
    add column if not exists tipo varchar(20) not null default 'desechable',
    add column if not exists scope_type varchar(20) not null default 'global',
    add column if not exists branch_id bigint null,
    add column if not exists controla_stock boolean not null default false,
    add column if not exists allow_negative_stock boolean not null default false,
    add column if not exists created_by_user_id bigint null,
    add column if not exists updated_by_user_id bigint null;

update public.inventory_items
set
    descripcion = coalesce(descripcion, null),
    tipo = coalesce(tipo, 'desechable'),
    scope_type = coalesce(scope_type, 'global'),
    branch_id = branch_id,
    controla_stock = coalesce(controla_stock, false),
    allow_negative_stock = coalesce(allow_negative_stock, false);

alter table public.inventory_items
    drop constraint if exists chk_inventory_items_tipo;

alter table public.inventory_items
    add constraint chk_inventory_items_tipo
    check (tipo in ('desechable', 'reusable'));

alter table public.inventory_items
    drop constraint if exists chk_inventory_items_scope_type;

alter table public.inventory_items
    add constraint chk_inventory_items_scope_type
    check (scope_type in ('global', 'sucursal'));

alter table public.inventory_items
    drop constraint if exists chk_inventory_items_scope_branch;

alter table public.inventory_items
    add constraint chk_inventory_items_scope_branch
    check (
        (scope_type = 'global' and branch_id is null)
        or (scope_type = 'sucursal' and branch_id is not null)
    );

do $$
begin
    if not exists (
        select 1
        from pg_constraint
        where conname = 'fk_inventory_items_branch_id_sucursales'
    ) then
        alter table public.inventory_items
            add constraint fk_inventory_items_branch_id_sucursales
            foreign key (branch_id)
            references public.sucursales(id)
            on delete restrict;
    end if;
end $$;

do $$
begin
    if not exists (
        select 1
        from pg_constraint
        where conname = 'fk_inventory_items_created_by_user_id_usuarios'
    ) then
        alter table public.inventory_items
            add constraint fk_inventory_items_created_by_user_id_usuarios
            foreign key (created_by_user_id)
            references public.usuarios(id)
            on delete restrict;
    end if;
end $$;

do $$
begin
    if not exists (
        select 1
        from pg_constraint
        where conname = 'fk_inventory_items_updated_by_user_id_usuarios'
    ) then
        alter table public.inventory_items
            add constraint fk_inventory_items_updated_by_user_id_usuarios
            foreign key (updated_by_user_id)
            references public.usuarios(id)
            on delete restrict;
    end if;
end $$;

create index if not exists idx_inventory_items_scope_type
    on public.inventory_items (scope_type);

create index if not exists idx_inventory_items_branch_id
    on public.inventory_items (branch_id);

create index if not exists idx_inventory_items_controla_stock
    on public.inventory_items (controla_stock);

create table if not exists public.inventory_stock_levels (
    id bigint generated by default as identity primary key,
    workspace_id bigint not null,
    inventory_item_id bigint not null,
    branch_id bigint not null,
    current_stock numeric(12, 2) not null default 0,
    minimum_stock numeric(12, 2) not null default 0,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint uq_inventory_stock_levels_item_branch
        unique (inventory_item_id, branch_id),
    constraint fk_inventory_stock_levels_workspace_id_workspaces
        foreign key (workspace_id)
        references public.workspaces(id)
        on delete cascade,
    constraint fk_inventory_stock_levels_inventory_item_id_inventory_items
        foreign key (inventory_item_id)
        references public.inventory_items(id)
        on delete cascade,
    constraint fk_inventory_stock_levels_branch_id_sucursales
        foreign key (branch_id)
        references public.sucursales(id)
        on delete restrict,
    constraint chk_inventory_stock_levels_minimum_stock
        check (minimum_stock >= 0)
);

create index if not exists idx_inventory_stock_levels_workspace_id
    on public.inventory_stock_levels (workspace_id);

create index if not exists idx_inventory_stock_levels_branch_id
    on public.inventory_stock_levels (branch_id);

create index if not exists idx_inventory_stock_levels_inventory_item_id
    on public.inventory_stock_levels (inventory_item_id);

drop trigger if exists trg_inventory_stock_levels_updated_at on public.inventory_stock_levels;
create trigger trg_inventory_stock_levels_updated_at
before update on public.inventory_stock_levels
for each row
execute function public.set_updated_at();

create table if not exists public.inventory_movements (
    id bigint generated by default as identity primary key,
    workspace_id bigint not null,
    inventory_item_id bigint not null,
    stock_level_id bigint not null,
    branch_id bigint not null,
    reservation_id bigint null,
    charge_id bigint null,
    movement_type varchar(20) not null,
    origin_type varchar(30) not null,
    quantity numeric(12, 2) not null,
    quantity_delta numeric(12, 2) not null,
    stock_before numeric(12, 2) not null,
    stock_after numeric(12, 2) not null,
    unit_cost_reference numeric(12, 2) not null default 0,
    created_by_user_id bigint not null,
    observation text null,
    created_at timestamptz not null default now(),
    constraint fk_inventory_movements_workspace_id_workspaces
        foreign key (workspace_id)
        references public.workspaces(id)
        on delete cascade,
    constraint fk_inventory_movements_inventory_item_id_inventory_items
        foreign key (inventory_item_id)
        references public.inventory_items(id)
        on delete cascade,
    constraint fk_inventory_movements_stock_level_id_inventory_stock_levels
        foreign key (stock_level_id)
        references public.inventory_stock_levels(id)
        on delete cascade,
    constraint fk_inventory_movements_branch_id_sucursales
        foreign key (branch_id)
        references public.sucursales(id)
        on delete restrict,
    constraint fk_inventory_movements_reservation_id_reservas
        foreign key (reservation_id)
        references public.reservas(id)
        on delete set null,
    constraint fk_inventory_movements_charge_id_reservation_charges
        foreign key (charge_id)
        references public.reservation_charges(id)
        on delete set null,
    constraint fk_inventory_movements_created_by_user_id_usuarios
        foreign key (created_by_user_id)
        references public.usuarios(id)
        on delete restrict,
    constraint chk_inventory_movements_movement_type
        check (movement_type in ('entrada', 'salida', 'ajuste', 'consumo', 'devolucion')),
    constraint chk_inventory_movements_origin_type
        check (origin_type in ('manual', 'procedure_report', 'item_creation')),
    constraint chk_inventory_movements_quantity
        check (quantity > 0),
    constraint chk_inventory_movements_quantity_delta
        check (quantity_delta <> 0),
    constraint chk_inventory_movements_unit_cost_reference
        check (unit_cost_reference >= 0)
);

create index if not exists idx_inventory_movements_workspace_id
    on public.inventory_movements (workspace_id);

create index if not exists idx_inventory_movements_item_id
    on public.inventory_movements (inventory_item_id);

create index if not exists idx_inventory_movements_branch_id
    on public.inventory_movements (branch_id);

create index if not exists idx_inventory_movements_created_at
    on public.inventory_movements (created_at desc);

create index if not exists idx_inventory_movements_charge_id
    on public.inventory_movements (charge_id);

create index if not exists idx_inventory_movements_reservation_id
    on public.inventory_movements (reservation_id);
