create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = current_timestamp;
  return new;
end;
$$;

create table if not exists public.usuarios (
    id bigint generated by default as identity primary key,
    nombre varchar(100) not null,
    correo varchar(150) not null,
    contrasena varchar(255) not null,
    rol varchar(50) not null,
    estado varchar(50) not null default 'activo',
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint uq_usuarios_correo unique (correo)
);

create index if not exists idx_usuarios_rol on public.usuarios (rol);
create index if not exists idx_usuarios_estado on public.usuarios (estado);

create table if not exists public.clinicas (
    id bigint generated by default as identity primary key,
    nombre varchar(120) not null,
    direccion varchar(255) not null,
    telefono varchar(20) not null,
    hora_apertura time not null,
    hora_cierre time not null,
    dias_laborales varchar(100) not null,
    estado varchar(50) not null default 'activa',
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint chk_clinicas_horario check (hora_cierre > hora_apertura)
);

create index if not exists idx_clinicas_estado on public.clinicas (estado);

create table if not exists public.salas (
    id bigint generated by default as identity primary key,
    nombre varchar(100) not null,
    tipo varchar(80) not null,
    descripcion varchar(255),
    estado varchar(50) not null default 'activa',
    capacidad integer not null default 1,
    disponibilidad varchar(50) not null default 'disponible',
    clinica_id bigint not null,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint fk_salas_clinica_id_clinicas
        foreign key (clinica_id)
        references public.clinicas(id)
        on delete no action
        on update no action,
    constraint chk_salas_capacidad check (capacidad >= 1)
);

create index if not exists idx_salas_clinica_id on public.salas (clinica_id);
create index if not exists idx_salas_estado on public.salas (estado);
create index if not exists idx_salas_disponibilidad on public.salas (disponibilidad);

create table if not exists public.pacientes (
    id bigint generated by default as identity primary key,
    nombre varchar(120) not null,
    fecha_nacimiento date,
    telefono varchar(20),
    correo varchar(150),
    observaciones varchar(255),
    estado varchar(50) not null default 'activo',
    tipo_procedimiento varchar(100),
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create index if not exists idx_pacientes_nombre on public.pacientes (nombre);
create index if not exists idx_pacientes_estado on public.pacientes (estado);
create index if not exists idx_pacientes_correo on public.pacientes (correo);

create table if not exists public.reservas (
    id bigint generated by default as identity primary key,
    fecha date not null,
    hora_inicio time not null,
    hora_fin time not null,
    descripcion varchar(255),
    estado varchar(50) not null default 'pendiente',
    tipo_consulta varchar(100),
    usuario_id bigint not null,
    paciente_id bigint not null,
    sala_id bigint not null,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint fk_reservas_usuario_id_usuarios
        foreign key (usuario_id)
        references public.usuarios(id)
        on delete no action
        on update no action,
    constraint fk_reservas_paciente_id_pacientes
        foreign key (paciente_id)
        references public.pacientes(id)
        on delete no action
        on update no action,
    constraint fk_reservas_sala_id_salas
        foreign key (sala_id)
        references public.salas(id)
        on delete no action
        on update no action,
    constraint chk_reservas_horas check (hora_fin > hora_inicio)
);

create index if not exists idx_reservas_usuario_id on public.reservas (usuario_id);
create index if not exists idx_reservas_paciente_id on public.reservas (paciente_id);
create index if not exists idx_reservas_sala_id on public.reservas (sala_id);
create index if not exists idx_reservas_fecha on public.reservas (fecha);
create index if not exists idx_reservas_estado on public.reservas (estado);
create index if not exists idx_reservas_sala_fecha on public.reservas (sala_id, fecha);

create table if not exists public.horarios_disponibles (
    id bigint generated by default as identity primary key,
    dia_semana varchar(15) not null,
    fecha date,
    hora_inicio time not null,
    hora_fin time not null,
    estado varchar(50) not null default 'disponible',
    sala_id bigint not null,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint fk_horarios_disponibles_sala_id_salas
        foreign key (sala_id)
        references public.salas(id)
        on delete no action
        on update no action,
    constraint chk_horarios_horas check (hora_fin > hora_inicio)
);

create index if not exists idx_horarios_sala_id on public.horarios_disponibles (sala_id);
create index if not exists idx_horarios_fecha on public.horarios_disponibles (fecha);
create index if not exists idx_horarios_estado on public.horarios_disponibles (estado);

drop trigger if exists trg_usuarios_updated_at on public.usuarios;
create trigger trg_usuarios_updated_at
before update on public.usuarios
for each row
execute function public.set_updated_at();

drop trigger if exists trg_clinicas_updated_at on public.clinicas;
create trigger trg_clinicas_updated_at
before update on public.clinicas
for each row
execute function public.set_updated_at();

drop trigger if exists trg_salas_updated_at on public.salas;
create trigger trg_salas_updated_at
before update on public.salas
for each row
execute function public.set_updated_at();

drop trigger if exists trg_pacientes_updated_at on public.pacientes;
create trigger trg_pacientes_updated_at
before update on public.pacientes
for each row
execute function public.set_updated_at();

drop trigger if exists trg_reservas_updated_at on public.reservas;
create trigger trg_reservas_updated_at
before update on public.reservas
for each row
execute function public.set_updated_at();

drop trigger if exists trg_horarios_disponibles_updated_at on public.horarios_disponibles;
create trigger trg_horarios_disponibles_updated_at
before update on public.horarios_disponibles
for each row
execute function public.set_updated_at();
