alter table public.workspace_settings
    add column if not exists document_mode varchar(30) not null default 'comprobante_simple',
    add column if not exists taxes_enabled boolean not null default false,
    add column if not exists no_show_policy varchar(30) not null default 'informativo',
    add column if not exists late_cancellation_policy varchar(30) not null default 'informativa',
    add column if not exists allow_reception_manual_charges boolean not null default true;

alter table public.workspace_settings
    drop constraint if exists chk_workspace_settings_document_mode;

alter table public.workspace_settings
    add constraint chk_workspace_settings_document_mode
    check (document_mode in ('comprobante_simple', 'prefactura'));

create table if not exists public.workspace_capabilities (
    id bigint generated by default as identity primary key,
    workspace_id bigint not null,
    finance_enabled boolean not null default true,
    inventory_enabled boolean not null default false,
    billable_catalog_enabled boolean not null default true,
    manual_billing_enabled boolean not null default false,
    partial_payments_enabled boolean not null default false,
    packages_enabled boolean not null default false,
    memberships_enabled boolean not null default false,
    rentals_enabled boolean not null default false,
    commissions_enabled boolean not null default false,
    deposits_enabled boolean not null default false,
    penalties_enabled boolean not null default false,
    whatsapp_enabled boolean not null default false,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint uq_workspace_capabilities_workspace_id unique (workspace_id),
    constraint fk_workspace_capabilities_workspace_id_workspaces
        foreign key (workspace_id)
        references public.workspaces(id)
        on delete cascade
);

create index if not exists idx_workspace_capabilities_workspace_id
    on public.workspace_capabilities (workspace_id);

insert into public.workspace_capabilities (
    workspace_id,
    finance_enabled,
    inventory_enabled,
    billable_catalog_enabled,
    manual_billing_enabled,
    partial_payments_enabled,
    packages_enabled,
    memberships_enabled,
    rentals_enabled,
    commissions_enabled,
    deposits_enabled,
    penalties_enabled,
    whatsapp_enabled
)
select
    w.id,
    true,
    case when coalesce(s.plan_code, 'basic') in ('premium', 'enterprise') then true else false end,
    true,
    case when coalesce(s.plan_code, 'basic') in ('premium', 'enterprise') then true else false end,
    case when coalesce(s.plan_code, 'basic') in ('premium', 'enterprise') then true else false end,
    false,
    false,
    case when coalesce(s.plan_code, 'basic') = 'enterprise' then true else false end,
    case when coalesce(s.plan_code, 'basic') = 'enterprise' then true else false end,
    case when coalesce(s.plan_code, 'basic') in ('premium', 'enterprise') then true else false end,
    case when coalesce(s.plan_code, 'basic') in ('premium', 'enterprise') then true else false end,
    false
from public.workspaces w
left join public.subscriptions s
    on s.workspace_id = w.id
where not exists (
    select 1
    from public.workspace_capabilities wc
    where wc.workspace_id = w.id
);

drop trigger if exists trg_workspace_capabilities_updated_at on public.workspace_capabilities;
create trigger trg_workspace_capabilities_updated_at
before update on public.workspace_capabilities
for each row
execute function public.set_updated_at();

create table if not exists public.billable_items (
    id bigint generated by default as identity primary key,
    workspace_id bigint not null,
    branch_id bigint null,
    name varchar(160) not null,
    description text null,
    category varchar(80) not null,
    appointment_type_hint varchar(30) not null default 'otro',
    base_price numeric(12, 2) not null default 0,
    currency_code varchar(10) not null default 'USD',
    tax_behavior varchar(30) not null default 'no_aplica',
    tax_rate numeric(5, 2) not null default 0,
    estimated_duration_minutes integer null,
    requires_patient boolean not null default true,
    requires_professional boolean not null default false,
    requires_room boolean not null default false,
    requires_inventory boolean not null default false,
    reservable boolean not null default false,
    billable_without_reservation boolean not null default true,
    package_eligible boolean not null default false,
    visible_to_reception boolean not null default true,
    administrative_only boolean not null default false,
    state varchar(20) not null default 'activo',
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint fk_billable_items_workspace_id_workspaces
        foreign key (workspace_id)
        references public.workspaces(id)
        on delete cascade,
    constraint fk_billable_items_branch_id_sucursales
        foreign key (branch_id)
        references public.sucursales(id)
        on delete set null,
    constraint chk_billable_items_state
        check (state in ('activo', 'inactivo')),
    constraint chk_billable_items_base_price
        check (base_price >= 0),
    constraint chk_billable_items_tax_rate
        check (tax_rate >= 0 and tax_rate <= 100),
    constraint chk_billable_items_duration
        check (estimated_duration_minutes is null or estimated_duration_minutes between 5 and 480),
    constraint chk_billable_items_appointment_type_hint
        check (appointment_type_hint in ('consulta', 'procedimiento', 'otro')),
    constraint chk_billable_items_tax_behavior
        check (tax_behavior in ('no_aplica', 'incluido', 'excluido'))
);

create index if not exists idx_billable_items_workspace_id
    on public.billable_items (workspace_id);

create index if not exists idx_billable_items_branch_id
    on public.billable_items (branch_id);

create index if not exists idx_billable_items_category
    on public.billable_items (category);

create index if not exists idx_billable_items_state
    on public.billable_items (state);

drop trigger if exists trg_billable_items_updated_at on public.billable_items;
create trigger trg_billable_items_updated_at
before update on public.billable_items
for each row
execute function public.set_updated_at();

create table if not exists public.billable_item_inventory_rules (
    id bigint generated by default as identity primary key,
    workspace_id bigint not null,
    billable_item_id bigint not null,
    inventory_item_id bigint not null,
    branch_id bigint null,
    quantity numeric(12, 2) not null default 1,
    apply_mode varchar(30) not null default 'por_evento',
    state varchar(20) not null default 'activo',
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint fk_billable_item_inventory_rules_workspace_id_workspaces
        foreign key (workspace_id)
        references public.workspaces(id)
        on delete cascade,
    constraint fk_billable_item_inventory_rules_billable_item_id_billable_items
        foreign key (billable_item_id)
        references public.billable_items(id)
        on delete cascade,
    constraint fk_billable_item_inventory_rules_inventory_item_id_inventory_items
        foreign key (inventory_item_id)
        references public.inventory_items(id)
        on delete cascade,
    constraint fk_billable_item_inventory_rules_branch_id_sucursales
        foreign key (branch_id)
        references public.sucursales(id)
        on delete set null,
    constraint chk_billable_item_inventory_rules_quantity
        check (quantity > 0),
    constraint chk_billable_item_inventory_rules_apply_mode
        check (apply_mode in ('por_evento', 'por_unidad')),
    constraint chk_billable_item_inventory_rules_state
        check (state in ('activo', 'inactivo'))
);

create index if not exists idx_billable_item_inventory_rules_workspace_id
    on public.billable_item_inventory_rules (workspace_id);

create index if not exists idx_billable_item_inventory_rules_billable_item_id
    on public.billable_item_inventory_rules (billable_item_id);

drop trigger if exists trg_billable_item_inventory_rules_updated_at on public.billable_item_inventory_rules;
create trigger trg_billable_item_inventory_rules_updated_at
before update on public.billable_item_inventory_rules
for each row
execute function public.set_updated_at();

alter table public.reservas
    add column if not exists billable_item_id bigint null;

do $$
begin
    if not exists (
        select 1
        from pg_constraint
        where conname = 'fk_reservas_billable_item_id_billable_items'
    ) then
        alter table public.reservas
            add constraint fk_reservas_billable_item_id_billable_items
            foreign key (billable_item_id)
            references public.billable_items(id)
            on delete set null;
    end if;
end $$;

create index if not exists idx_reservas_billable_item_id
    on public.reservas (billable_item_id);

alter table public.reservation_charges
    add column if not exists billable_item_id bigint null;

do $$
begin
    if not exists (
        select 1
        from pg_constraint
        where conname = 'fk_reservation_charges_billable_item_id_billable_items'
    ) then
        alter table public.reservation_charges
            add constraint fk_reservation_charges_billable_item_id_billable_items
            foreign key (billable_item_id)
            references public.billable_items(id)
            on delete set null;
    end if;
end $$;

create index if not exists idx_reservation_charges_billable_item_id
    on public.reservation_charges (billable_item_id);

create table if not exists public.billing_documents (
    id bigint generated by default as identity primary key,
    workspace_id bigint not null,
    branch_id bigint null,
    reservation_id bigint null,
    patient_id bigint null,
    patient_name_snapshot varchar(150) null,
    patient_phone_snapshot varchar(50) null,
    professional_user_id bigint null,
    professional_name_snapshot varchar(150) null,
    room_id bigint null,
    room_name_snapshot varchar(150) null,
    source_type varchar(40) not null default 'manual',
    source_id bigint null,
    party_type varchar(20) not null default 'patient',
    party_id bigint null,
    document_type varchar(30) not null default 'comprobante_simple',
    document_status varchar(30) not null default 'emitido',
    currency_code varchar(10) not null default 'USD',
    subtotal_amount numeric(12, 2) not null default 0,
    tax_amount numeric(12, 2) not null default 0,
    discount_amount numeric(12, 2) not null default 0,
    total_amount numeric(12, 2) not null default 0,
    charge_decision varchar(30) not null default 'cobrable',
    notes text null,
    issued_at timestamptz not null default now(),
    issued_by_user_id bigint not null,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint fk_billing_documents_workspace_id_workspaces
        foreign key (workspace_id)
        references public.workspaces(id)
        on delete cascade,
    constraint fk_billing_documents_branch_id_sucursales
        foreign key (branch_id)
        references public.sucursales(id)
        on delete set null,
    constraint fk_billing_documents_reservation_id_reservas
        foreign key (reservation_id)
        references public.reservas(id)
        on delete set null,
    constraint fk_billing_documents_patient_id_pacientes
        foreign key (patient_id)
        references public.pacientes(id)
        on delete set null,
    constraint fk_billing_documents_professional_user_id_usuarios
        foreign key (professional_user_id)
        references public.usuarios(id)
        on delete set null,
    constraint fk_billing_documents_room_id_salas
        foreign key (room_id)
        references public.salas(id)
        on delete set null,
    constraint fk_billing_documents_issued_by_user_id_usuarios
        foreign key (issued_by_user_id)
        references public.usuarios(id)
        on delete restrict,
    constraint chk_billing_documents_source_type
        check (source_type in ('reservation', 'manual', 'rental', 'deposit', 'adjustment')),
    constraint chk_billing_documents_party_type
        check (party_type in ('patient', 'professional', 'workspace', 'external')),
    constraint chk_billing_documents_document_type
        check (document_type in ('comprobante_simple', 'prefactura')),
    constraint chk_billing_documents_document_status
        check (document_status in ('emitido', 'anulado')),
    constraint chk_billing_documents_charge_decision
        check (charge_decision in ('cobrable', 'exonerado')),
    constraint chk_billing_documents_amounts
        check (
            subtotal_amount >= 0
            and tax_amount >= 0
            and discount_amount >= 0
            and total_amount >= 0
        )
);

create index if not exists idx_billing_documents_workspace_id
    on public.billing_documents (workspace_id);

create index if not exists idx_billing_documents_reservation_id
    on public.billing_documents (reservation_id);

create index if not exists idx_billing_documents_document_status
    on public.billing_documents (document_status);

create unique index if not exists uq_billing_documents_active_reservation
    on public.billing_documents (reservation_id)
    where reservation_id is not null and document_status <> 'anulado';

drop trigger if exists trg_billing_documents_updated_at on public.billing_documents;
create trigger trg_billing_documents_updated_at
before update on public.billing_documents
for each row
execute function public.set_updated_at();

create table if not exists public.billing_document_lines (
    id bigint generated by default as identity primary key,
    workspace_id bigint not null,
    document_id bigint not null,
    billable_item_id bigint null,
    line_name_snapshot varchar(160) not null,
    description_snapshot text null,
    category_snapshot varchar(80) null,
    quantity numeric(12, 2) not null default 1,
    unit_price numeric(12, 2) not null default 0,
    discount_amount numeric(12, 2) not null default 0,
    tax_rate numeric(5, 2) not null default 0,
    tax_amount numeric(12, 2) not null default 0,
    line_total numeric(12, 2) not null default 0,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint fk_billing_document_lines_workspace_id_workspaces
        foreign key (workspace_id)
        references public.workspaces(id)
        on delete cascade,
    constraint fk_billing_document_lines_document_id_billing_documents
        foreign key (document_id)
        references public.billing_documents(id)
        on delete cascade,
    constraint fk_billing_document_lines_billable_item_id_billable_items
        foreign key (billable_item_id)
        references public.billable_items(id)
        on delete set null,
    constraint chk_billing_document_lines_amounts
        check (
            quantity > 0
            and unit_price >= 0
            and discount_amount >= 0
            and tax_rate >= 0
            and tax_rate <= 100
            and tax_amount >= 0
            and line_total >= 0
        )
);

create index if not exists idx_billing_document_lines_workspace_id
    on public.billing_document_lines (workspace_id);

create index if not exists idx_billing_document_lines_document_id
    on public.billing_document_lines (document_id);

drop trigger if exists trg_billing_document_lines_updated_at on public.billing_document_lines;
create trigger trg_billing_document_lines_updated_at
before update on public.billing_document_lines
for each row
execute function public.set_updated_at();

create table if not exists public.billing_document_payments (
    id bigint generated by default as identity primary key,
    workspace_id bigint not null,
    document_id bigint not null,
    amount numeric(12, 2) not null,
    currency_code varchar(10) not null,
    payment_method varchar(30) not null,
    paid_at timestamptz not null,
    notes text null,
    registered_by_user_id bigint not null,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint fk_billing_document_payments_workspace_id_workspaces
        foreign key (workspace_id)
        references public.workspaces(id)
        on delete cascade,
    constraint fk_billing_document_payments_document_id_billing_documents
        foreign key (document_id)
        references public.billing_documents(id)
        on delete cascade,
    constraint fk_billing_document_payments_registered_by_user_id_usuarios
        foreign key (registered_by_user_id)
        references public.usuarios(id)
        on delete restrict,
    constraint chk_billing_document_payments_amount
        check (amount > 0),
    constraint chk_billing_document_payments_payment_method
        check (payment_method in ('efectivo', 'tarjeta', 'transferencia', 'otro'))
);

create index if not exists idx_billing_document_payments_workspace_id
    on public.billing_document_payments (workspace_id);

create index if not exists idx_billing_document_payments_document_id
    on public.billing_document_payments (document_id);

create index if not exists idx_billing_document_payments_paid_at
    on public.billing_document_payments (paid_at desc);

drop trigger if exists trg_billing_document_payments_updated_at on public.billing_document_payments;
create trigger trg_billing_document_payments_updated_at
before update on public.billing_document_payments
for each row
execute function public.set_updated_at();

create or replace view public.billing_document_financials as
with payment_agg as (
    select
        bdp.workspace_id,
        bdp.document_id,
        coalesce(sum(bdp.amount), 0)::numeric(12, 2) as paid_amount,
        count(*)::int as payment_count,
        max(bdp.paid_at) as last_payment_at
    from public.billing_document_payments bdp
    group by bdp.workspace_id, bdp.document_id
)
select
    bd.workspace_id,
    bd.id as document_id,
    bd.reservation_id,
    bd.currency_code,
    bd.document_status,
    bd.charge_decision,
    bd.total_amount::numeric(12, 2) as total_amount,
    coalesce(pa.paid_amount, 0)::numeric(12, 2) as paid_amount,
    greatest(
        bd.total_amount::numeric(12, 2) - coalesce(pa.paid_amount, 0)::numeric(12, 2),
        0::numeric
    )::numeric(12, 2) as outstanding_amount,
    coalesce(pa.payment_count, 0) as payment_count,
    pa.last_payment_at,
    case
        when bd.charge_decision = 'exonerado' then 'exonerado'
        when bd.document_status = 'anulado' then 'anulado'
        when greatest(
            bd.total_amount::numeric(12, 2) - coalesce(pa.paid_amount, 0)::numeric(12, 2),
            0::numeric
        ) = 0::numeric then 'pagado'
        when coalesce(pa.paid_amount, 0)::numeric(12, 2) > 0::numeric then 'parcial'
        else 'pendiente'
    end as financial_status
from public.billing_documents bd
left join payment_agg pa
    on pa.document_id = bd.id
   and pa.workspace_id = bd.workspace_id;
