alter table public.workspace_settings
    add column if not exists default_procedure_pricing_mode varchar(30) not null default 'solo_sala';

alter table public.workspace_settings
    drop constraint if exists chk_workspace_settings_default_procedure_pricing_mode;

alter table public.workspace_settings
    add constraint chk_workspace_settings_default_procedure_pricing_mode
    check (
        default_procedure_pricing_mode in ('solo_sala', 'solo_insumos', 'sala_mas_insumos')
    );

alter table public.reservation_charges
    add column if not exists pricing_mode varchar(30) not null default 'solo_sala',
    add column if not exists room_charge_amount numeric(12, 2) not null default 0,
    add column if not exists supplies_total_amount numeric(12, 2) not null default 0,
    add column if not exists supplies_total_cost numeric(12, 2) not null default 0,
    add column if not exists total_billed_amount numeric(12, 2) not null default 0,
    add column if not exists charge_decision varchar(30) not null default 'cobrable',
    add column if not exists waived_by_user_id bigint null,
    add column if not exists waiver_reason text null;

update public.reservation_charges
set
    pricing_mode = coalesce(pricing_mode, 'solo_sala'),
    room_charge_amount = case
        when room_charge_amount > 0 then room_charge_amount
        else coalesce(amount, 0)
    end,
    supplies_total_amount = coalesce(supplies_total_amount, 0),
    supplies_total_cost = coalesce(supplies_total_cost, 0),
    total_billed_amount = case
        when total_billed_amount > 0 then total_billed_amount
        else coalesce(amount, 0)
    end,
    charge_decision = coalesce(charge_decision, 'cobrable');

do $$
begin
    if not exists (
        select 1
        from pg_constraint
        where conname = 'fk_reservation_charges_waived_by_user_id_usuarios'
    ) then
        alter table public.reservation_charges
            add constraint fk_reservation_charges_waived_by_user_id_usuarios
            foreign key (waived_by_user_id)
            references public.usuarios(id)
            on delete restrict;
    end if;
end $$;

alter table public.reservation_charges
    drop constraint if exists chk_reservation_charges_pricing_mode;

alter table public.reservation_charges
    add constraint chk_reservation_charges_pricing_mode
    check (pricing_mode in ('solo_sala', 'solo_insumos', 'sala_mas_insumos'));

alter table public.reservation_charges
    drop constraint if exists chk_reservation_charges_charge_decision;

alter table public.reservation_charges
    add constraint chk_reservation_charges_charge_decision
    check (charge_decision in ('cobrable', 'exonerado'));

alter table public.reservation_charges
    drop constraint if exists chk_reservation_charges_room_charge_amount;

alter table public.reservation_charges
    add constraint chk_reservation_charges_room_charge_amount
    check (room_charge_amount >= 0);

alter table public.reservation_charges
    drop constraint if exists chk_reservation_charges_supplies_total_amount;

alter table public.reservation_charges
    add constraint chk_reservation_charges_supplies_total_amount
    check (supplies_total_amount >= 0);

alter table public.reservation_charges
    drop constraint if exists chk_reservation_charges_supplies_total_cost;

alter table public.reservation_charges
    add constraint chk_reservation_charges_supplies_total_cost
    check (supplies_total_cost >= 0);

alter table public.reservation_charges
    drop constraint if exists chk_reservation_charges_total_billed_amount;

alter table public.reservation_charges
    add constraint chk_reservation_charges_total_billed_amount
    check (total_billed_amount >= 0);

alter table public.reservation_charges
    drop constraint if exists chk_reservation_charges_waiver_reason;

alter table public.reservation_charges
    add constraint chk_reservation_charges_waiver_reason
    check (
        (charge_decision = 'cobrable' and waiver_reason is null)
        or (
            charge_decision = 'exonerado'
            and waiver_reason is not null
            and char_length(trim(waiver_reason)) > 0
        )
    );

create index if not exists idx_reservation_charges_charge_decision
    on public.reservation_charges (charge_decision);

create table if not exists public.inventory_items (
    id bigint generated by default as identity primary key,
    workspace_id bigint not null,
    nombre varchar(150) not null,
    categoria varchar(80),
    unidad varchar(40) not null default 'unidad',
    costo_base numeric(12, 2) not null default 0,
    precio_sugerido numeric(12, 2) not null default 0,
    estado varchar(20) not null default 'activo',
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint fk_inventory_items_workspace_id_workspaces
        foreign key (workspace_id)
        references public.workspaces(id)
        on delete cascade,
    constraint chk_inventory_items_estado
        check (estado in ('activo', 'inactivo')),
    constraint chk_inventory_items_costo_base
        check (costo_base >= 0),
    constraint chk_inventory_items_precio_sugerido
        check (precio_sugerido >= 0)
);

create index if not exists idx_inventory_items_workspace_id
    on public.inventory_items (workspace_id);

create index if not exists idx_inventory_items_estado
    on public.inventory_items (estado);

drop trigger if exists trg_inventory_items_updated_at on public.inventory_items;
create trigger trg_inventory_items_updated_at
before update on public.inventory_items
for each row
execute function public.set_updated_at();

create table if not exists public.reservation_charge_supplies (
    id bigint generated by default as identity primary key,
    workspace_id bigint not null,
    charge_id bigint not null,
    inventory_item_id bigint null,
    item_name_snapshot varchar(150) not null,
    item_category_snapshot varchar(80),
    unit_snapshot varchar(40) not null default 'unidad',
    quantity numeric(12, 2) not null,
    unit_cost numeric(12, 2) not null default 0,
    unit_price numeric(12, 2) not null default 0,
    subtotal_cost numeric(12, 2) not null default 0,
    subtotal_price numeric(12, 2) not null default 0,
    notes text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint fk_reservation_charge_supplies_workspace_id_workspaces
        foreign key (workspace_id)
        references public.workspaces(id)
        on delete cascade,
    constraint fk_reservation_charge_supplies_charge_id_reservation_charges
        foreign key (charge_id)
        references public.reservation_charges(id)
        on delete cascade,
    constraint fk_reservation_charge_supplies_inventory_item_id_inventory_items
        foreign key (inventory_item_id)
        references public.inventory_items(id)
        on delete set null,
    constraint chk_reservation_charge_supplies_quantity
        check (quantity > 0),
    constraint chk_reservation_charge_supplies_unit_cost
        check (unit_cost >= 0),
    constraint chk_reservation_charge_supplies_unit_price
        check (unit_price >= 0),
    constraint chk_reservation_charge_supplies_subtotal_cost
        check (subtotal_cost >= 0),
    constraint chk_reservation_charge_supplies_subtotal_price
        check (subtotal_price >= 0)
);

create index if not exists idx_reservation_charge_supplies_workspace_id
    on public.reservation_charge_supplies (workspace_id);

create index if not exists idx_reservation_charge_supplies_charge_id
    on public.reservation_charge_supplies (charge_id);

drop trigger if exists trg_reservation_charge_supplies_updated_at on public.reservation_charge_supplies;
create trigger trg_reservation_charge_supplies_updated_at
before update on public.reservation_charge_supplies
for each row
execute function public.set_updated_at();
