alter table public.reservas
    add column if not exists appointment_outcome varchar(30) not null default 'pendiente',
    add column if not exists confirmed_at timestamptz null,
    add column if not exists confirmed_by_user_id bigint null,
    add column if not exists cancelled_at timestamptz null,
    add column if not exists cancelled_by_user_id bigint null,
    add column if not exists cancellation_reason text null,
    add column if not exists checked_in_at timestamptz null,
    add column if not exists completed_at timestamptz null,
    add column if not exists outcome_recorded_at timestamptz null,
    add column if not exists outcome_recorded_by_user_id bigint null;

update public.reservas
set appointment_outcome = case
    when estado = 'cancelada' then 'cancelada'
    else coalesce(appointment_outcome, 'pendiente')
end;

alter table public.reservas
    drop constraint if exists chk_reservas_appointment_outcome;

alter table public.reservas
    add constraint chk_reservas_appointment_outcome
    check (appointment_outcome in ('pendiente', 'atendida', 'no_show', 'cancelada'));

do $$
begin
    if not exists (
        select 1
        from pg_constraint
        where conname = 'fk_reservas_confirmed_by_user_id_usuarios'
    ) then
        alter table public.reservas
            add constraint fk_reservas_confirmed_by_user_id_usuarios
            foreign key (confirmed_by_user_id)
            references public.usuarios(id)
            on delete set null;
    end if;
end $$;

do $$
begin
    if not exists (
        select 1
        from pg_constraint
        where conname = 'fk_reservas_cancelled_by_user_id_usuarios'
    ) then
        alter table public.reservas
            add constraint fk_reservas_cancelled_by_user_id_usuarios
            foreign key (cancelled_by_user_id)
            references public.usuarios(id)
            on delete set null;
    end if;
end $$;

do $$
begin
    if not exists (
        select 1
        from pg_constraint
        where conname = 'fk_reservas_outcome_recorded_by_user_id_usuarios'
    ) then
        alter table public.reservas
            add constraint fk_reservas_outcome_recorded_by_user_id_usuarios
            foreign key (outcome_recorded_by_user_id)
            references public.usuarios(id)
            on delete set null;
    end if;
end $$;

create index if not exists idx_reservas_appointment_outcome_fecha
    on public.reservas (workspace_id, appointment_outcome, fecha);

create index if not exists idx_reservas_confirmed_at
    on public.reservas (workspace_id, confirmed_at);

create index if not exists idx_reservas_cancelled_at
    on public.reservas (workspace_id, cancelled_at)
    where cancelled_at is not null;

create index if not exists idx_reservas_completed_at
    on public.reservas (workspace_id, completed_at)
    where completed_at is not null;

create table if not exists public.kpi_daily_snapshots (
    id bigint generated by default as identity primary key,
    workspace_id bigint not null,
    metric_date date not null,
    grain_type varchar(30) not null,
    branch_id bigint null,
    room_id bigint null,
    doctor_user_id bigint null,
    procedure_name varchar(150) null,
    currency_code varchar(10) null,
    scheduled_count integer not null default 0,
    confirmed_count integer not null default 0,
    cancelled_count integer not null default 0,
    attended_count integer not null default 0,
    no_show_count integer not null default 0,
    booked_minutes integer not null default 0,
    operational_minutes integer not null default 0,
    idle_minutes integer not null default 0,
    paid_revenue numeric(12, 2) not null default 0,
    pending_revenue numeric(12, 2) not null default 0,
    exonerated_amount numeric(12, 2) not null default 0,
    supplies_cost numeric(12, 2) not null default 0,
    gross_margin_amount numeric(12, 2) not null default 0,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint fk_kpi_daily_snapshots_workspace_id_workspaces
        foreign key (workspace_id)
        references public.workspaces(id)
        on delete cascade,
    constraint fk_kpi_daily_snapshots_branch_id_sucursales
        foreign key (branch_id)
        references public.sucursales(id)
        on delete set null,
    constraint fk_kpi_daily_snapshots_room_id_salas
        foreign key (room_id)
        references public.salas(id)
        on delete set null,
    constraint fk_kpi_daily_snapshots_doctor_user_id_usuarios
        foreign key (doctor_user_id)
        references public.usuarios(id)
        on delete set null,
    constraint chk_kpi_daily_snapshots_grain_type
        check (grain_type in ('workspace', 'branch', 'room', 'doctor', 'procedure'))
);

create index if not exists idx_kpi_daily_snapshots_workspace_date
    on public.kpi_daily_snapshots (workspace_id, metric_date);

create index if not exists idx_kpi_daily_snapshots_grain
    on public.kpi_daily_snapshots (workspace_id, grain_type, metric_date);

drop trigger if exists trg_kpi_daily_snapshots_updated_at on public.kpi_daily_snapshots;
create trigger trg_kpi_daily_snapshots_updated_at
before update on public.kpi_daily_snapshots
for each row
execute function public.set_updated_at();

create or replace view public.vw_kpi_reservation_facts as
select
    r.workspace_id,
    r.id as reservation_id,
    r.fecha as reservation_date,
    r.created_at as reservation_created_at,
    r.updated_at as reservation_updated_at,
    r.estado as reservation_status,
    r.appointment_outcome,
    r.tipo_atencion,
    r.tipo_consulta,
    r.confirmed_at,
    r.confirmed_by_user_id,
    r.cancelled_at,
    r.cancelled_by_user_id,
    r.cancellation_reason,
    r.checked_in_at,
    r.completed_at,
    r.outcome_recorded_at,
    r.outcome_recorded_by_user_id,
    r.usuario_id as reservation_user_id,
    u.nombre as reservation_user_name,
    r.paciente_id,
    p.nombre as patient_name,
    r.sala_id as room_id,
    s.nombre as room_name,
    s.estado as room_status,
    s.sucursal_id as branch_id,
    su.nombre as branch_name,
    greatest(
        0,
        floor(extract(epoch from (r.hora_fin - r.hora_inicio)) / 60)
    )::int as duration_minutes,
    rc.id as charge_id,
    rc.payment_status,
    rc.payment_method,
    rc.paid_at,
    rc.currency_code,
    rc.charge_decision,
    rc.pricing_mode,
    coalesce(rc.room_charge_amount, 0) as room_charge_amount,
    coalesce(rc.supplies_total_amount, 0) as supplies_total_amount,
    coalesce(rc.supplies_total_cost, 0) as supplies_total_cost,
    coalesce(rc.total_billed_amount, rc.amount, 0) as total_billed_amount,
    case
        when rc.charge_decision = 'cobrable' and rc.payment_status = 'pagado'
            then coalesce(rc.total_billed_amount, rc.amount, 0)
        else 0
    end as paid_revenue,
    case
        when rc.charge_decision = 'cobrable' and rc.payment_status = 'pendiente'
            then coalesce(rc.total_billed_amount, rc.amount, 0)
        else 0
    end as pending_revenue,
    case
        when rc.charge_decision = 'exonerado'
            then coalesce(rc.total_billed_amount, rc.amount, 0)
        else 0
    end as exonerated_amount,
    case
        when rc.charge_decision = 'cobrable' and rc.payment_status = 'pagado'
            then coalesce(rc.total_billed_amount, rc.amount, 0) - coalesce(rc.supplies_total_cost, 0)
        else null
    end as gross_margin_amount
from public.reservas r
left join public.usuarios u
    on u.id = r.usuario_id
left join public.pacientes p
    on p.id = r.paciente_id
   and p.workspace_id = r.workspace_id
left join public.salas s
    on s.id = r.sala_id
   and s.workspace_id = r.workspace_id
left join public.sucursales su
    on su.id = s.sucursal_id
left join public.reservation_charges rc
    on rc.reservation_id = r.id
   and rc.workspace_id = r.workspace_id;
