alter table public.workspace_members
    drop constraint if exists chk_workspace_members_role;

alter table public.workspace_members
    add constraint chk_workspace_members_role
    check (role in ('owner', 'admin', 'recepcionista', 'doctor', 'staff'));

alter table public.workspace_settings
    add column if not exists consultation_open_time time not null default '08:00:00',
    add column if not exists consultation_close_time time null default '17:00:00',
    add column if not exists consultation_no_closing boolean not null default false,
    add column if not exists procedure_open_time time not null default '08:00:00',
    add column if not exists procedure_close_time time null default '17:00:00',
    add column if not exists procedure_no_closing boolean not null default false,
    add column if not exists time_zone varchar(80) not null default 'America/Costa_Rica';

update public.workspace_settings ws
set
    consultation_open_time = coalesce(c.hora_apertura, ws.consultation_open_time),
    consultation_close_time = coalesce(c.hora_cierre, ws.consultation_close_time),
    procedure_open_time = coalesce(c.hora_apertura, ws.procedure_open_time),
    procedure_close_time = coalesce(c.hora_cierre, ws.procedure_close_time)
from public.clinicas c
where c.workspace_id = ws.workspace_id;

alter table public.workspace_settings
    drop constraint if exists chk_workspace_settings_consultation_hours;

alter table public.workspace_settings
    add constraint chk_workspace_settings_consultation_hours
    check (
        (
            consultation_no_closing = true
            and consultation_open_time is not null
        )
        or (
            consultation_no_closing = false
            and consultation_open_time is not null
            and consultation_close_time is not null
            and consultation_close_time > consultation_open_time
        )
    );

alter table public.workspace_settings
    drop constraint if exists chk_workspace_settings_procedure_hours;

alter table public.workspace_settings
    add constraint chk_workspace_settings_procedure_hours
    check (
        (
            procedure_no_closing = true
            and procedure_open_time is not null
        )
        or (
            procedure_no_closing = false
            and procedure_open_time is not null
            and procedure_close_time is not null
            and procedure_close_time > procedure_open_time
        )
    );

alter table public.reservas
    add column if not exists tipo_atencion varchar(30);

update public.reservas
set tipo_atencion = case
    when lower(coalesce(tipo_consulta, '')) like '%cirug%' then 'procedimiento'
    when lower(coalesce(tipo_consulta, '')) like '%quirur%' then 'procedimiento'
    when lower(coalesce(tipo_consulta, '')) like '%proced%' then 'procedimiento'
    when lower(coalesce(tipo_consulta, '')) like '%laparo%' then 'procedimiento'
    when lower(coalesce(tipo_consulta, '')) like '%endosc%' then 'procedimiento'
    when lower(coalesce(tipo_consulta, '')) like '%biops%' then 'procedimiento'
    when lower(coalesce(tipo_consulta, '')) like '%interven%' then 'procedimiento'
    else 'consulta'
end
where tipo_atencion is null;

alter table public.reservas
    alter column tipo_atencion set default 'consulta';

alter table public.reservas
    alter column tipo_atencion set not null;

alter table public.reservas
    drop constraint if exists chk_reservas_tipo_atencion;

alter table public.reservas
    add constraint chk_reservas_tipo_atencion
    check (tipo_atencion in ('consulta', 'procedimiento'));

create index if not exists idx_reservas_tipo_atencion
    on public.reservas (tipo_atencion);

create table if not exists public.reservation_charges (
    id bigint generated by default as identity primary key,
    workspace_id bigint not null,
    reservation_id bigint not null,
    patient_id bigint not null,
    patient_name_snapshot varchar(150) not null,
    room_id bigint not null,
    room_name_snapshot varchar(150) not null,
    branch_id bigint null,
    branch_name_snapshot varchar(150),
    procedure_name varchar(150) not null,
    tipo_atencion varchar(30) not null,
    amount numeric(12, 2) not null,
    currency_code varchar(10) not null default 'CRC',
    payment_status varchar(30) not null default 'pendiente',
    payment_method varchar(30) not null default 'otro',
    paid_at timestamptz null,
    registered_by_user_id bigint not null,
    notes text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint uq_reservation_charges_reservation_id unique (reservation_id),
    constraint fk_reservation_charges_workspace_id_workspaces
        foreign key (workspace_id)
        references public.workspaces(id)
        on delete cascade,
    constraint fk_reservation_charges_reservation_id_reservas
        foreign key (reservation_id)
        references public.reservas(id)
        on delete cascade,
    constraint fk_reservation_charges_patient_id_pacientes
        foreign key (patient_id)
        references public.pacientes(id)
        on delete restrict,
    constraint fk_reservation_charges_room_id_salas
        foreign key (room_id)
        references public.salas(id)
        on delete restrict,
    constraint fk_reservation_charges_branch_id_sucursales
        foreign key (branch_id)
        references public.sucursales(id)
        on delete set null,
    constraint fk_reservation_charges_registered_by_user_id_usuarios
        foreign key (registered_by_user_id)
        references public.usuarios(id)
        on delete restrict,
    constraint chk_reservation_charges_tipo_atencion
        check (tipo_atencion in ('consulta', 'procedimiento')),
    constraint chk_reservation_charges_payment_status
        check (payment_status in ('pendiente', 'pagado', 'anulado')),
    constraint chk_reservation_charges_payment_method
        check (payment_method in ('efectivo', 'tarjeta', 'transferencia', 'otro')),
    constraint chk_reservation_charges_amount
        check (amount >= 0)
);

create index if not exists idx_reservation_charges_workspace_id
    on public.reservation_charges (workspace_id);

create index if not exists idx_reservation_charges_payment_status
    on public.reservation_charges (payment_status);

create index if not exists idx_reservation_charges_paid_at
    on public.reservation_charges (paid_at);

create index if not exists idx_reservation_charges_room_id
    on public.reservation_charges (room_id);

drop trigger if exists trg_reservation_charges_updated_at on public.reservation_charges;
create trigger trg_reservation_charges_updated_at
before update on public.reservation_charges
for each row
execute function public.set_updated_at();
