create table if not exists public.workspaces (
    id bigint generated by default as identity primary key,
    nombre varchar(120) not null,
    slug varchar(160) not null,
    estado varchar(50) not null default 'activo',
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint uq_workspaces_slug unique (slug),
    constraint chk_workspaces_estado
        check (estado in ('activo', 'suspendido', 'cancelado'))
);

create index if not exists idx_workspaces_estado on public.workspaces (estado);

create table if not exists public.workspace_members (
    id bigint generated by default as identity primary key,
    workspace_id bigint not null,
    usuario_id bigint not null,
    role varchar(50) not null,
    estado varchar(50) not null default 'activo',
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint fk_workspace_members_workspace_id_workspaces
        foreign key (workspace_id)
        references public.workspaces(id)
        on delete cascade
        on update no action,
    constraint fk_workspace_members_usuario_id_usuarios
        foreign key (usuario_id)
        references public.usuarios(id)
        on delete cascade
        on update no action,
    constraint uq_workspace_members_workspace_usuario unique (workspace_id, usuario_id),
    constraint chk_workspace_members_role
        check (role in ('owner', 'admin', 'staff')),
    constraint chk_workspace_members_estado
        check (estado in ('activo', 'invitado', 'suspendido'))
);

create index if not exists idx_workspace_members_workspace_id
    on public.workspace_members (workspace_id);
create index if not exists idx_workspace_members_usuario_id
    on public.workspace_members (usuario_id);

create table if not exists public.subscriptions (
    id bigint generated by default as identity primary key,
    workspace_id bigint not null,
    plan_code varchar(50) not null,
    commercial_status varchar(50) not null,
    billing_mode varchar(50) not null default 'paid',
    trial_ends_at timestamptz,
    current_period_ends_at timestamptz,
    max_users integer not null,
    max_rooms integer not null,
    max_reservations_per_month integer not null,
    partner_valid_until timestamptz,
    partner_notes varchar(255),
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint uq_subscriptions_workspace_id unique (workspace_id),
    constraint fk_subscriptions_workspace_id_workspaces
        foreign key (workspace_id)
        references public.workspaces(id)
        on delete cascade
        on update no action,
    constraint chk_subscriptions_plan_code
        check (plan_code in ('basic', 'premium', 'enterprise')),
    constraint chk_subscriptions_commercial_status
        check (
            commercial_status in (
                'trial',
                'active',
                'partner_comped',
                'past_due',
                'canceled',
                'suspended'
            )
        ),
    constraint chk_subscriptions_billing_mode
        check (billing_mode in ('paid', 'comped')),
    constraint chk_subscriptions_limits
        check (
            max_users >= 1 and
            max_rooms >= 1 and
            max_reservations_per_month >= 1
        )
);

create index if not exists idx_subscriptions_plan_code on public.subscriptions (plan_code);
create index if not exists idx_subscriptions_commercial_status
    on public.subscriptions (commercial_status);

alter table public.clinicas
    add column if not exists workspace_id bigint;

alter table public.salas
    add column if not exists workspace_id bigint;

alter table public.pacientes
    add column if not exists workspace_id bigint;

alter table public.reservas
    add column if not exists workspace_id bigint;

insert into public.workspaces (nombre, slug, estado)
select
    'Agendo Legacy',
    'agendo-legacy',
    'activo'
where (
    exists (select 1 from public.usuarios)
    or exists (select 1 from public.pacientes)
    or exists (select 1 from public.reservas)
)
  and not exists (select 1 from public.clinicas)
  and not exists (
      select 1
      from public.workspaces
      where slug = 'agendo-legacy'
  );

insert into public.workspaces (nombre, slug, estado)
select
    coalesce(nullif(trim(c.nombre), ''), 'Clinica Legacy ' || c.id),
    'legacy-clinic-' || c.id,
    'activo'
from public.clinicas c
where not exists (
    select 1
    from public.workspaces w
    where w.slug = 'legacy-clinic-' || c.id
);

update public.clinicas c
set workspace_id = w.id
from public.workspaces w
where w.slug = 'legacy-clinic-' || c.id;

update public.salas s
set workspace_id = c.workspace_id
from public.clinicas c
where s.clinica_id = c.id
  and s.workspace_id is null;

update public.reservas r
set workspace_id = s.workspace_id
from public.salas s
where r.sala_id = s.id
  and r.workspace_id is null;

update public.pacientes p
set workspace_id = resumen.workspace_id
from (
    select
        r.paciente_id,
        min(r.workspace_id) as workspace_id
    from public.reservas r
    where r.workspace_id is not null
    group by r.paciente_id
) resumen
where p.id = resumen.paciente_id
  and p.workspace_id is null;

update public.pacientes p
set workspace_id = fallback.workspace_id
from (
    select c.workspace_id
    from public.clinicas c
    where c.workspace_id is not null
    order by c.id asc
    limit 1
) fallback
where p.workspace_id is null;

update public.pacientes
set workspace_id = (
    select id
    from public.workspaces
    where slug = 'agendo-legacy'
)
where workspace_id is null
  and exists (
      select 1
      from public.workspaces
      where slug = 'agendo-legacy'
  );

do $$
begin
    if not exists (
        select 1
        from pg_constraint
        where conname = 'fk_clinicas_workspace_id_workspaces'
    ) then
        alter table public.clinicas
            add constraint fk_clinicas_workspace_id_workspaces
            foreign key (workspace_id)
            references public.workspaces(id)
            on delete cascade
            on update no action;
    end if;
end
$$;

do $$
begin
    if not exists (
        select 1
        from pg_constraint
        where conname = 'fk_salas_workspace_id_workspaces'
    ) then
        alter table public.salas
            add constraint fk_salas_workspace_id_workspaces
            foreign key (workspace_id)
            references public.workspaces(id)
            on delete cascade
            on update no action;
    end if;
end
$$;

do $$
begin
    if not exists (
        select 1
        from pg_constraint
        where conname = 'fk_pacientes_workspace_id_workspaces'
    ) then
        alter table public.pacientes
            add constraint fk_pacientes_workspace_id_workspaces
            foreign key (workspace_id)
            references public.workspaces(id)
            on delete cascade
            on update no action;
    end if;
end
$$;

do $$
begin
    if not exists (
        select 1
        from pg_constraint
        where conname = 'fk_reservas_workspace_id_workspaces'
    ) then
        alter table public.reservas
            add constraint fk_reservas_workspace_id_workspaces
            foreign key (workspace_id)
            references public.workspaces(id)
            on delete cascade
            on update no action;
    end if;
end
$$;

create index if not exists idx_clinicas_workspace_id on public.clinicas (workspace_id);
create index if not exists idx_salas_workspace_id on public.salas (workspace_id);
create index if not exists idx_pacientes_workspace_id on public.pacientes (workspace_id);
create index if not exists idx_reservas_workspace_id on public.reservas (workspace_id);

create unique index if not exists uq_clinicas_workspace_id
    on public.clinicas (workspace_id);

alter table public.clinicas
    alter column workspace_id set not null;

alter table public.salas
    alter column workspace_id set not null;

alter table public.pacientes
    alter column workspace_id set not null;

alter table public.reservas
    alter column workspace_id set not null;

insert into public.workspace_members (workspace_id, usuario_id, role, estado)
select
    w.id,
    u.id,
    'owner',
    'activo'
from public.workspaces w
cross join public.usuarios u
where (
      w.slug = 'agendo-legacy'
      or w.slug like 'legacy-clinic-%'
  )
  and not exists (
      select 1
      from public.workspace_members wm
      where wm.workspace_id = w.id
        and wm.usuario_id = u.id
  );

insert into public.subscriptions (
    workspace_id,
    plan_code,
    commercial_status,
    billing_mode,
    trial_ends_at,
    current_period_ends_at,
    max_users,
    max_rooms,
    max_reservations_per_month
)
select
    w.id,
    'basic',
    'active',
    'paid',
    null,
    now() + interval '30 days',
    3,
    3,
    500
from public.workspaces w
where (
      w.slug = 'agendo-legacy'
      or w.slug like 'legacy-clinic-%'
  )
  and not exists (
      select 1
      from public.subscriptions s
      where s.workspace_id = w.id
  );

drop trigger if exists trg_workspaces_updated_at on public.workspaces;
create trigger trg_workspaces_updated_at
before update on public.workspaces
for each row
execute function public.set_updated_at();

drop trigger if exists trg_workspace_members_updated_at on public.workspace_members;
create trigger trg_workspace_members_updated_at
before update on public.workspace_members
for each row
execute function public.set_updated_at();

drop trigger if exists trg_subscriptions_updated_at on public.subscriptions;
create trigger trg_subscriptions_updated_at
before update on public.subscriptions
for each row
execute function public.set_updated_at();
