create table if not exists public.workspace_settings (
    id bigint generated by default as identity primary key,
    workspace_id bigint not null,
    consultation_duration_minutes integer not null default 30,
    procedure_duration_minutes integer not null default 60,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint uq_workspace_settings_workspace_id unique (workspace_id),
    constraint fk_workspace_settings_workspace_id_workspaces
        foreign key (workspace_id)
        references public.workspaces(id)
        on delete cascade
        on update no action,
    constraint chk_workspace_settings_consultation_duration
        check (consultation_duration_minutes between 5 and 480),
    constraint chk_workspace_settings_procedure_duration
        check (procedure_duration_minutes between 5 and 480)
);

create index if not exists idx_workspace_settings_workspace_id
    on public.workspace_settings (workspace_id);

insert into public.workspace_settings (
    workspace_id,
    consultation_duration_minutes,
    procedure_duration_minutes
)
select
    w.id,
    30,
    60
from public.workspaces w
where not exists (
    select 1
    from public.workspace_settings ws
    where ws.workspace_id = w.id
);

drop trigger if exists trg_workspace_settings_updated_at on public.workspace_settings;
create trigger trg_workspace_settings_updated_at
before update on public.workspace_settings
for each row
execute function public.set_updated_at();
