create table if not exists public.sucursales (
    id bigint generated by default as identity primary key,
    workspace_id bigint not null,
    nombre varchar(120) not null,
    codigo varchar(80) not null,
    direccion varchar(255),
    telefono varchar(20),
    estado varchar(50) not null default 'activa',
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint fk_sucursales_workspace_id_workspaces
        foreign key (workspace_id)
        references public.workspaces(id)
        on delete cascade
        on update no action,
    constraint chk_sucursales_estado
        check (estado in ('activa', 'inactiva'))
);

create index if not exists idx_sucursales_workspace_id
    on public.sucursales (workspace_id);
create index if not exists idx_sucursales_estado
    on public.sucursales (estado);
create unique index if not exists uq_sucursales_workspace_codigo
    on public.sucursales (workspace_id, codigo);

alter table public.salas
    add column if not exists sucursal_id bigint;

alter table public.workspace_members
    add column if not exists sucursal_id bigint;

insert into public.sucursales (
    workspace_id,
    nombre,
    codigo,
    direccion,
    telefono,
    estado
)
select
    w.id,
    'Sucursal principal',
    'principal',
    c.direccion,
    c.telefono,
    'activa'
from public.workspaces w
left join public.clinicas c
    on c.workspace_id = w.id
where not exists (
    select 1
    from public.sucursales s
    where s.workspace_id = w.id
);

update public.salas sa
set sucursal_id = sp.id
from public.sucursales sp
where sp.workspace_id = sa.workspace_id
  and sp.codigo = 'principal'
  and sa.sucursal_id is null;

update public.workspace_members wm
set sucursal_id = sp.id
from public.sucursales sp
where sp.workspace_id = wm.workspace_id
  and sp.codigo = 'principal'
  and wm.sucursal_id is null
  and wm.estado = 'activo';

do $$
begin
    if not exists (
        select 1
        from pg_constraint
        where conname = 'fk_salas_sucursal_id_sucursales'
    ) then
        alter table public.salas
            add constraint fk_salas_sucursal_id_sucursales
            foreign key (sucursal_id)
            references public.sucursales(id)
            on delete no action
            on update no action;
    end if;
end
$$;

do $$
begin
    if not exists (
        select 1
        from pg_constraint
        where conname = 'fk_workspace_members_sucursal_id_sucursales'
    ) then
        alter table public.workspace_members
            add constraint fk_workspace_members_sucursal_id_sucursales
            foreign key (sucursal_id)
            references public.sucursales(id)
            on delete set null
            on update no action;
    end if;
end
$$;

create index if not exists idx_salas_sucursal_id
    on public.salas (sucursal_id);
create index if not exists idx_workspace_members_sucursal_id
    on public.workspace_members (sucursal_id);

alter table public.salas
    alter column sucursal_id set not null;

drop trigger if exists trg_sucursales_updated_at on public.sucursales;
create trigger trg_sucursales_updated_at
before update on public.sucursales
for each row
execute function public.set_updated_at();
